version: '3.7'
services:
  backend:
    build: .
    links:
      - db:mysql
    ports:
      - 3001:3001
    volumes:
      - ./web-gpu-rendering/backend:/home/golem/app
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: mydb
